apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: "true"
  name: kcc-firewall-test
spec:
  allow: 
    - protocol: tcp
      ports: 
      - "80"
      - "8080"
      - "433"
      - "22"      
  direction: "INGRESS"
  priority: 1000
  networkRef:
      name: kcc-firewall-test
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: kcc-firewall-test
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
